### PR TITLE
 Better JSON formatting, and more thorough hardcoded secret details

### PR DESCRIPTION
**Pull request by rahiparikh**
The current JSON formatting had some parsing issues for edge cases. The pull request tries to resolve the issues, improve formatting, and add more details in hardcoded secrets for JSON formatting.

### CODE REVIEW

**Comment by rahiparikh** [comment]
The current JSON formatting had some parsing issues for edge cases. The pull request tries to resolve the issues, improve formatting, and add more details in hardcoded secrets for JSON formatting.

**Comment by GriffinMB** [comment]
This is great, thank you!! This is a significant improvement to the JSON handling.

Would you mind updating the PR to remove the Poison dependency (it looks like you don't use it in the end), and also update/improve the test case at "test/log_test.exs" so that it passes?

**Comment by GriffinMB** [comment]
I made a few small updates, and tweaked the test. Thanks again for the PR!

**Comment by rahiparikh** [comment]
@GriffinMB Were you able to release newer version of SoBelow?

**Comment by GriffinMB** [comment]
Just did :)

**Pull request merged**
