### PR TITLE
Allow atom values for threshold in config file.

### PR DESCRIPTION
**Pull request by hassan**
Assumes this is OK :-)

Addresses issue #95  (https://github.com/nccgroup/sobelow/issues/95)

### CODE REVIEW

**Comment by GriffinMB** [comment]
Excellent, thanks for the PR! Could you make the same update for line 216? Feel free to pull that functionality out into its own function.

**Comment by hassan** [comment]
Since those two examples have different case statements, it probably doesn't add a lot to try to split them out into a function (as much as I enjoy refactoring!)

Cheers 😀

**Comment by GriffinMB** [comment]
Sorry for the delayed merge, it's been a busy week! Thanks again for the PR :)

**Comment by hassan** [comment]
Thank _you_ for the great tool. Glad to be able to contribute!

**Pull request merged**
